---
- job:
    name: golang-coverage
    parent: unittests
    pre-run: playbooks/coverage/pre-run.yaml
    run: playbooks/coverage/run.yaml


- project:
    check:
      jobs:
      - golangci-lint
      - golang-go-test
      - golang-coverage
    gate:
      jobs:
      - golangci-lint
      - golang-go-test
      - golang-coverage
