---
- job:
    name: golang-coverage
    pre-run: playbooks/functional/pre.yaml
    run: playbooks/functional/run.yaml
- project:
    templates:
    - golang-jobs
    check:
      jobs:
      - golang-coverage
    gate:
      jobs:
      - golang-coverage
