---
- job:
    name: golang-coverage
    parent: golang-go
    vars:
      go_command: test -coverprofile fmtcoverage.html fmt

- project:
    templates:
    - golang-jobs
    check:
      jobs:
      - golangci-lint
      - golanggo-test
      - golang-coverage
    gate:
      jobs:
      - golangci-lint
      - golanggo-test
      - golang-coverage
