---
- job:
    name: golang-coverage
    parent: golang-go
    vars:
      go_command: "test -coverprofile fmtcoverage.html fmt"

- project:
    check:
      jobs:
      - golangci-lint
      - golang-go-test
      - golang-coverage
    gate:
      jobs:
      - golangci-lint
      - golang-go-test
      - golang-coverage
