---
- job:
    name: golang-coverage
    run: playbooks/functional/coverage.yaml
- project:
    templates:
    - golang-jobs
    check:
      jobs:
      - golang-coverage
    gate:
      jobs:
      - golang-coverage
