---
- job:
    name: golang-coverage
    parent: unittests
    run: playbooks/coverage.yaml


- project:
    check:
      jobs:
      - golangci-lint
      - golang-go-test
      - golang-coverage
    gate:
      jobs:
      - golangci-lint
      - golang-go-test
      - golang-coverage
